const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('index.html','utf8');
const part=(a,b)=>html.slice(html.indexOf(a),html.indexOf(b));
const ctx=vm.createContext({console,Date,crypto:require('node:crypto'),navigator:{onLine:false}});
vm.runInContext(`let settings={base:21875,daily:8000,tiers:[{min:90,rate:7},{min:100,rate:11},{min:136,rate:15}]},days=[],orders=[],viewMonth;\n${part('const pad=','/* ================= RENDER: TODAY')}\n${part('function primaryTier','function dailyTierMarkup')}\n${part('const KINDS=','function renderMonth')}\nfunction persist(){} function renderMonth(){} function pushPending(){} function queue(){} const uid=()=>crypto.randomUUID(); todayIso=()=> '2026-09-21'; remainingDays=s=>s.wd.filter(d=>d>=todayIso()).length;`,ctx);
const run=s=>vm.runInContext(s,ctx);
assert.equal(run("monthStats('2026-09').target"),168000);
assert.equal(run("monthStats('2026-09').wd.length"),21);
run("orders=[{date:'2026-09-18',amount:100000}]");
const budget=run("dailyTierStats(monthStats('2026-09'),{min:100}).target");assert.equal(budget,68000/7);
run("orders.push({date:'2026-09-21',amount:5000})");assert.equal(run("dailyTierStats(monthStats('2026-09'),{min:100}).target"),budget);
run("cycleMark('2026-09-22')");assert.equal(run("dayMark('2026-09-22').kind"),'dovolena');assert.equal(run("monthStats('2026-09').target"),160000);assert.equal(run("monthStats('2026-09').wd.length"),20);
run("cycleMark('2026-09-22')");assert.equal(run("dayMark('2026-09-22').kind"),'volno');assert.equal(run("monthStats('2026-09').target"),168000);assert.equal(run("dailyTierStats(monthStats('2026-09'),{min:100}).target"),68000/6);
run("cycleMark('2026-09-22')");assert.equal(run("dayMark('2026-09-22')"),undefined);assert.equal(run("monthStats('2026-09').wd.length"),21);
run("cycleMark('2026-09-21')");assert.equal(run("dailyTierStats(monthStats('2026-09'),{min:100}).target"),null);
run("days=[];orders=[{date:'2026-09-18',amount:300000}]");assert.equal(run("dailyTierStats(monthStats('2026-09'),{min:136}).target"),0);
run("cycleMark('2026-09-28')");assert.equal(run('days.length'),0);
console.log('PASS: fund, daily budget stability, vacation/leave cycle, nonworking day, reached tier, holiday');
(async()=>{
 const sync=vm.createContext({navigator:{onLine:true},console});
 vm.runInContext(`let pending=[{table:'day_marks',row:{id:'test',kind:'dovolena'}}],sbUser={id:'synthetic'},LS={pending:'pending'};let releases=[],written=[];const save=()=>{},cloudStatus=()=>{};const sb={from:()=>({upsert:rows=>new Promise(resolve=>{written.push(rows[0].kind);releases.push(()=>resolve({error:null}))})})};${part('let pendingPush=null;','async function pullAll')}`,sync);
 const initial=vm.runInContext('pushPending()',sync);
 vm.runInContext("pending=[{table:'day_marks',row:{id:'test',kind:'volno'}}];pushPending();releases.shift()()",sync);
 await new Promise(r=>setImmediate(r));
 assert.equal(vm.runInContext('written.join(",")',sync),'dovolena,volno');
 vm.runInContext('releases.shift()()',sync);await initial;
 assert.equal(vm.runInContext('pending.length',sync),0);
 console.log('PASS: serialized cloud queue keeps the newest calendar state (mocked service)');
})().catch(e=>{console.error(e);process.exitCode=1});
